### ISSUE TITLE
AttributeError when starting rocon_qt_app_manager

### ISSUE THREAD

**Issue by mikepurvis** [robotics-in-concert/rocon_qt_gui#147] opened 2014-08-20 17:23 UTC
Not sure if I'm doing something else wrong, but this is on Trusty + Indigo, running the following in two separate tabs:

```
roslaunch rocon_app_manager standalone.launch
ROS_NAMESPACE=cybernetic_pirate rosrun rocon_qt_app_manager rocon_qt_app_manager
```

However, rocon_qt_app_manager bombs out with the following error:

```
Traceback (most recent call last):
  File "/home/administrator/rocon_ws/src/rocon_qt_gui/rocon_qt_app_manager/src/rocon_qt_app_manager/qt_app_manager.py", line 112, in _change_namespace
    self.qt_rapp_manager_info._get_rapps(self._widget.namespace_cbox.currentText())
  File "/home/administrator/rocon_ws/src/rocon_qt_gui/rocon_qt_app_manager/src/rocon_qt_app_manager/qt_app_manager_info.py", line 95, in _get_rapps
    self._update_rapps(service_handle())
  File "/home/administrator/rocon_ws/src/rocon_qt_gui/rocon_qt_app_manager/src/rocon_qt_app_manager/qt_app_manager_info.py", line 60, in _update_rapps
    self.rapps = list_rapp_msg_to_dict(data.available_rapps)
  File "/home/administrator/rocon_ws/src/rocon_qt_gui/rocon_qt_app_manager/src/rocon_qt_app_manager/qt_app_manager_info.py", line 37, in list_rapp_msg_to_dict
    dict_rapp[rapp]["preferred"] = rapp.preferred
AttributeError: 'Rapp' object has no attribute 'preferred'
```

Seems to affect both the `indigo` and `hydro-devel` branches. I can get the GUI to appear by commenting out various of these lines, but there are further issues upon attempting to actually launch a rapp.

Is there an interface inconsistency between app manager and the rest of rocon? Is there something else I should be using for an app launcher in my robot's RQT dashboard?

**Comment by jihoonl** [comment] 2014-08-21 00:53
There was major update on rocon_app_manager which affected the rest of rocon in two months. 

PR #143 and #142  and PR in rocon_app_manager https://github.com/robotics-in-concert/rocon_app_platform/pull/248 are related with your issue.

If you use source version of rocon_app_manager and rocon_qt_gui, you should not have any problem.
The deb version and source version are out of sync. I plan to re-release packages with new feature in near future

**Comment by mikepurvis** [comment] 2014-08-21 14:07
Okay, I now have a source workspace with `rocon_app_platform`, `rocon_concert`, `rocon_msgs`, and `rocon_qt_gui` in it. I'm able to start the standalone app manager and the QT GUI, and start the talker app. However, when I stop the app, I get another similar error:

```
[INFO] [WallTime: 1408629921.640618] Rapp Manager : Stopping rapp 'rocon_apps/talker'.
[ERROR] [WallTime: 1408629921.641807] Error processing request: 'rocon_apps/talker'
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/administrator/rocon_ws/src/rocon_app_platform/rocon_app_manager/src/rocon_app_manager/rapp_manager.py", line 602, in _process_stop_app\n    resp.stopped, resp.message, subscribers, publishers, services, action_clients, action_servers = self._runnable_apps[rapp_name].stop()\n', "KeyError: 'rocon_apps/talker'\n"]
```

Also, it's a bummer how developer-y `rocon_qt_app_manager` looks. Is there a plan to create an app-launcher GUI which is closer to just being an icon grid?

**Comment by jihoonl** [comment] 2014-08-25 06:52
> Okay, I now have a source workspace with `rocon_app_platform`, `rocon_concert`, `rocon_msgs`, and `rocon_qt_gui` in it. I'm able to start the standalone app manager and the QT GUI, and start the talker app. However, when I stop the app, I get another similar error: ....

Hm... I was testing with indigo branch and I didn't get the error message. Can you provide instruction  how you started the program?

I did the following

```
> roslaunch rocon_app_manager standalone.launch --screen
> rocon_qt_app_manager
## Start rocon_apps/talker in qt app manager
```

> Also, it's a bummer how developer-y `rocon_qt_app_manager` looks. Is there a plan to create an app-launcher GUI which is closer to just being an icon grid?

Haha actually it was developed just for experiments and testing purpose. :)
We don't have any plan to upgrade its design yet since it satisfied what I needed for.

But I would love to see and use if anybody neatly designed QT app manager :smile_cat:

**Comment by stonier** [comment] 2014-09-11 03:52
I can reproduce Mike's error Jihoon. Come see me and see if we can work out where it's coming from.

**Comment by stonier** [comment] 2014-09-11 03:53
And eesh, I agree with Mike - first time I've used this (I'm typically running full concerts) and it is rather unbeautiful :P

**Comment by stonier** [comment] 2014-09-11 04:04
Fixed in indigo branches with https://github.com/robotics-in-concert/rocon_msgs/commit/060ea74ef2cde419997b1061efbb2cdd0e832e16 and https://github.com/robotics-in-concert/rocon_app_platform/commit/853796b9bd2c55c9450a09d9e4dad957c88f6a29

**Comment by stonier** [comment] 2014-09-11 04:06
Opened a new issue to polish the qt rapp manager at #149.

**Closed as completed by stonier** 2014-09-11 04:06 UTC
